version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.20.4
    steps:
      - checkout
      - run:
          name: Sample command
          command: echo "This is a basic config"

workflows:
  workflow:
    jobs:
      - build